const express = require("express");
const router = express.Router();
const control = require("../controllers/engageToConf");
router.get('/getEngagedConf/:user_id', control.getEnngagedConfWhereUser);
router.get('/getAllTestimonial', control.getAllTestimonials);
router.get('/getAllTestimonialSelected', control.getAllTestimonialsSelected);
router.post("/engageToConference", control.EngageToConf);
router.post("/engageToConferenceAsSpeaker", control.EngageToConfAsSpeaker);
router.put("/updateToSelected/:id", control.UpdateToSelectedTestimonial);
router.put("/updateToNOTSelected/:id", control.UpdateToNOTSelectedTestimonial);
router.post("/AddTestimonial/:user_id", control.AddTestimonial);
router.delete('/deleteTestimonial/:id',control.deleteTestimonial);
module.exports = router;