const express = require("express");
const multer = require('multer');
const upload = multer({ storage: multer.memoryStorage() });
const router = express.Router();
const control = require("../controllers/userController");
router.get("/getAll", control.getAllUsers);
router.get("/getAllActiveUsers", control.getAllUsersActive);
router.get("/getAllNonActiveUsers", control.getAllUsersNonActive);
router.get("/getUsersByRole/:role", control.getAllUsersByRole);
router.get("/getUserByEmail/:email", control.getUsersByEmail);
router.get("/getUserByFullName/:fullName", control.getAllUsersByFullName);
router.post('/register',upload.single('img'), control.register);
router.put('/editUser/:id',upload.single('img'), control.updateUser);
router.put('/updateToActiveUser/:id',control.switchToActivateUser);
router.put('/updateToNonActiveUser/:id',control.switchToNonActivateUser);
router.post('/login',control.loginUser);
router.delete('/deleteUser/:id',control.deleteUser);
module.exports = router;