const express = require("express");
const router = express.Router();
const control = require("../controllers/userController");
router.get("/getAll", control.getAllUsers);
router.get("/getAllActiveUsers", control.getAllUsersActive);
router.get("/getAllNonActiveUsers", control.getAllUsersNonActive);
router.get("/getUsersByRole/:role", control.getAllUsersByRole);
router.get("/getUserByEmail/:email", control.getUsersByEmail);
router.get("/getUserByFullName/:fullName", control.getAllUsersByFullName);
router.post('/register', control.register);
router.post('/addUser', control.AddUser);
router.put('/editUser/:id', control.updateUser);
router.put('/AdminUpdateUser/:id',control.AdminupdateUser);
router.put('/switchToTrainer/:id',control.switchToTrainer);
router.put('/switchToStudent/:id',control.switchToStudent);
router.put('/updateToActiveUser/:id',control.switchToActivateUser);
router.put('/updateToNonActiveUser/:id',control.switchToNonActivateUser);
router.post('/login',control.loginUser);
router.post('/loginGoogle',control.loginUserGoogle);
router.delete('/deleteUser/:id',control.deleteUser);
module.exports = router;